### ISSUE TITLE
Reason for another Go yaml parser?

### ISSUE THREAD

**Issue by aarondl** [cloudfoundry-incubator/candiedyaml#15]
I used this parser with the gorouter component recently and found it frustratingly bad at producing quality error messages often quoting the wrong line numbers entirely and rather than start filing bugs against this repo I thought I would point to (what I would consider the Go defacto-standard) yaml parser: https://github.com/go-yaml/yaml/ and ask why it wasn't being used.

A quick search reveals that this parser is almost exclusively used within the cloudfoundry ecosystem:
http://go-search.org/view?id=github.com%2fcloudfoundry-incubator%2fcandiedyaml

Whereas the implementation I've mentioned is used by a much more broad audience hinting at it's maturity, quality and spec adherence.
http://go-search.org/view?id=gopkg.in%2fyaml.v2

Just wanted to ask the question. Thoughts?

**Comment by lox** [comment]
https://github.com/docker/libcompose/issues/79 O_o

**Comment by aarondl** [comment]
This issue: https://www.pivotaltracker.com/story/show/93072208 was created shortly after I opened this issue. Whether that's coincidence or intentionally hiding the issue details I'm not sure. Basically the PM there is saying that there's no licensing concerns for CF at least, so I'm still curious why this library is being used - especially when other CF components are moving away from it. A non-LGPL alternative is a good reason if that were a concern but it doesn't look that way.

**Comment by ematpl** [comment]
Hey, @aarondl,

Apologies for letting this slip through the cracks. My understanding is that @fraenkel created candiedyaml and we forked it into cloudfoundry-incubator for use in CF projects precisely because of apprehension about the modified LGPL license from https://github.com/go-yaml/yaml/. Since then, some CF projects have switched back to the go-yaml library, notably the [CF CLI](https://github.com/cloudfoundry/cli) and [bosh-init](https://github.com/cloudfoundry/bosh-init). In reference to the Diego tracker story you linked to, I'd like to get strong confirmation from the CF Foundation and/or key Foundation members that the licensing on go-yaml is indeed acceptable for use before switching any of the CF Diego components over to use it, despite those other projects' decisions.

Thanks,
Eric, CF Runtime Diego PM

**Comment by aarondl** [comment]
The update is much appreciated @ematpl, thank you. Will stand by for the decision and will happily accept whatever's decided.

**Comment by tony** [comment]
(L)GPLv3 spoils the go-yaml/yaml project completely. You can't port the code to other licenses in the future - even if the terms don't affect your current situation, 99% you'll end up rewriting it anyway since you don't feel a yaml library should be dictating the future of your project.

**Comment by niemeyer** [comment]
FWIW, there's no reason go-yaml's license should "dictate the future of your project". If you have any real concerns, please do get in touch and I'll be happy to understand and address them.

**Comment by niemeyer** [comment]
Also, please note that this is a ripoff from go-yaml. I can clearly see my own code in several options of this library. If you are worried about licenses, you are doing it wrong.

**Comment by sparkprime** [comment]
Am I right that go-yaml does not support yaml streams, whereas this code does?

**Comment by fabian-z** [comment]
@niemeyer 
Can you clarify on your claims? I did a quick search with [CPD (from PMD 5.5)](https://github.com/pmd/pmd) and the results seem to be a result of the common fundamental principle of being a port of libyaml: [Results](https://gist.github.com/fabian-z/f0093c8c4ad2aefc1121770e1af7f59f). 

Obviously an automated search is per definition not as thorough as your check, so I would like to ask you to point out the points which are problematic from your point of view for community review.

On a side note, I do also think that the license choice of the great go-yaml project you helped to build imposes legal uncertainty on a very nice library:
Basically custom exceptions, additions or other changes to established licenses always require any involved party (including the end-using company) to involve lawyers and check if their use is covered by the license. This is because all the widely available, established interpretation and compatibility analyses for all the licenses are worthless with your custom exception/addition/removal/etc. This legal council may even be required multiple times, depending on the use case. Also compatibility with other licenses must be checked by experienced professionals.

Since this is unreasonable for individual developers, smaller companies and startups, I think it is important to have an alternative to go-yaml which imposes a less restrictive and from a legal  standpoint less uncertain license. In contrast to that, the Apache license is an established license and also mirrors the original freedoms granted by libyaml more closely.

With that being said, in my opinion clarifying your claims on this project and, if at all possible, relicensing go-yaml to a standard OSI license would be the best outcome for the Go community.

**Comment by tony** [comment]
>  If you have any real concerns, please do get in touch and I'll be happy to understand and address them.

Do you actually expect people to check in with you and confide their problem with you? How would their explaining help, it wouldn’t be a “real concern”.  Why would they bother?

Have you read the GPL and understand its incompatible with practically all other open source licenses, as well as most commercial purposes? Are you aware of the implications as to why people can’t use the license?  Are you aware that many people sympathize with the GPL but can't use it anyway due to their jobs?

**Comment by niemeyer** [comment]
@tony You're misjudging me. I too would rather re-license, and in fact we have a long on-going thread on this very topic internally, including lawyers. There's a chance we'll manage to move it. If I ask for concrete data, it's not because I expect you to do anything, but because I'm both trying to help and gathering data about the problem to improve the chances of re-licensing. Feel free to ignore me, though.

@fabian-z There are design decisions in go-yaml that did not come from libyaml, and I know those because I've made them in the first place. Please note I'm not threatening anything, though (I'm not even the copyrighter, to be clear). I'm just sad, rather than upset, about this being the case and people choosing to redo the work rather than collaborating.

**Comment by karlkfi** [comment]
Looks like go-yaml has been recently re-licensed to Apache 2 (with libyaml ported bits as MIT). Tho it looks like the readme is out of date now.

Given that, is there a compelling reason to keep using/maintaining this project?

**Comment by emalm** [comment]
Hi, @aarondl,

The `candiedyaml` library is now deprecated in favor of other YAML libraries such as [`gopkg.in/yaml.v2`](https://gopkg.in/yaml.v2) and is no longer under active development, so I'm closing out this issue.

Best,
Eric, Cloud Foundry Diego PM
